"""add sanaei users table

Revision ID: 1a289c145515
Revises: 851f6f93fec0
Create Date: 2026-05-06 17:30:01.825566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a289c145515'
down_revision: Union[str, None] = '851f6f93fec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sanaei_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sanaei_users_id'), 'sanaei_users', ['id'], unique=False)
    op.create_index(op.f('ix_sanaei_users_username'), 'sanaei_users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sanaei_users_username'), table_name='sanaei_users')
    op.drop_index(op.f('ix_sanaei_users_id'), table_name='sanaei_users')
    op.drop_table('sanaei_users')
    # ### end Alembic commands ###
