"""Added sublink url in panels table

Revision ID: 55d743570ead
Revises: 74a537c1229a
Create Date: 2025-12-08 22:20:20.610581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55d743570ead'
down_revision: Union[str, None] = '74a537c1229a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panels', sa.Column('sub_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('panels', 'sub_url')
    # ### end Alembic commands ###
