"""Updated Panels tabel

Revision ID: 74a537c1229a
Revises: f647e9ec504c
Create Date: 2025-12-05 13:30:45.943344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a537c1229a'
down_revision: Union[str, None] = 'f647e9ec504c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panels', sa.Column('password', sa.String(), nullable=False))
    op.drop_column('panels', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panels', sa.Column('hashed_password', sa.VARCHAR(), nullable=False))
    op.drop_column('panels', 'password')
    # ### end Alembic commands ###
