"""add delete_return_traffic

Revision ID: 851f6f93fec0
Revises: cd9f70ff69d4
Create Date: 2026-02-21 06:07:14.542348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851f6f93fec0'
down_revision: Union[str, None] = 'cd9f70ff69d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('update_return_traffic', sa.Boolean(), nullable=True, server_default=sa.false()))
    op.add_column('admins', sa.Column('delete_return_traffic', sa.Boolean(), nullable=True, server_default=sa.false()))
    op.drop_column('admins', 'return_traffic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('return_traffic', sa.BOOLEAN(), nullable=True))
    op.drop_column('admins', 'delete_return_traffic')
    op.drop_column('admins', 'update_return_traffic')
    # ### end Alembic commands ###
