"""add guardusers table

Revision ID: 8c82eb6a7c50
Revises: 8f29a226b288
Create Date: 2026-06-03 07:03:27.183359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c82eb6a7c50'
down_revision: Union[str, None] = '8f29a226b288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guard_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guard_users_id'), 'guard_users', ['id'], unique=False)
    op.create_index(op.f('ix_guard_users_username'), 'guard_users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guard_users_username'), table_name='guard_users')
    op.drop_index(op.f('ix_guard_users_id'), table_name='guard_users')
    op.drop_table('guard_users')
    # ### end Alembic commands ###
