"""add inbound flow for admins

Revision ID: 93535f2c172b
Revises: eea09b134fd7
Create Date: 2026-02-09 17:36:50.136703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93535f2c172b'
down_revision: Union[str, None] = 'eea09b134fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('inbound_flow', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'inbound_flow')
    # ### end Alembic commands ###
