"""added Marzban inbounds for admins

Revision ID: b9d190c16f53
Revises: 4c5e03dbd6ae
Create Date: 2025-12-29 13:35:54.654231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d190c16f53'
down_revision: Union[str, None] = '4c5e03dbd6ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('marzban_inbounds', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'marzban_inbunds')
    # ### end Alembic commands ###
