"""added Marzban pass for admins

Revision ID: eea09b134fd7
Revises: b9d190c16f53
Create Date: 2026-01-01 11:59:48.233468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eea09b134fd7'
down_revision: Union[str, None] = 'b9d190c16f53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('marzban_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'marzban_password')
    # ### end Alembic commands ###
